name: Python Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run docker container
      run: |
          echo ">>>> Start Docker Container <<<<"
          docker-compose up -d
          echo ">>>> Check Docker Processes <<<<"
          docker ps -a
          echo ">>>> Check Docker Images <<<<"
          docker images -a
          
